spring:
  application:
    name: consul-example
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
      config:
        enabled: true


